### ISSUE TITLE
some build failures not sending emails

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#67]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/67)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
http://build.osrfoundation.org/view/main/view/GazeboRelease/job/gazebo-ci-gazebo7-homebrew-amd64/26/console

~~~
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
ERROR: Could not send email as a part of the post-build publishers.
java.lang.NullPointerException
	at hudson.plugins.emailext.ExtendedEmailPublisher.sendMail(ExtendedEmailPublisher.java:378)
	at hudson.plugins.emailext.ExtendedEmailPublisher._perform(ExtendedEmailPublisher.java:350)
	at hudson.plugins.emailext.ExtendedEmailPublisher.perform(ExtendedEmailPublisher.java:258)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:195)
	at hudson.model.Run.execute(Run.java:1788)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Finished: FAILURE
~~~

**Comment by j-rivero** [comment]
please reopen if still present.
